### ISSUE TITLE
OS compatibility and PCL module

### ISSUE THREAD

**Issue by marco-ambrosio** [JackFrost67/pgm2pcd#1]
Hello JackFrost67!
First of all, thank you for your work, it is really interesting!

I need just a couple of clarifications:

1. Which OS are you working on? Windows or Linux?
2. Which Python PCL module did you used?

If you can add this informations also to the readme it would be very helpful. 
Thanks, Marco

**Comment by JackFrost67** [comment]
1. Linux 
2. Sorry for not putting the requirements.txt, but actually it should work with any version of PCL. I used the 1.13.0

**Comment by marco-ambrosio** [comment]
Sorry to bother you, but which python package are you using?
I can not find a way to import pcl in a python script

**Comment by marco-ambrosio** [comment]
I managed to do it. I used the `python3-pcl` and `libpcl-dev` packages provided by apt
